server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.88.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.88.128:9300
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 30 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}